version: "3.9"

services:
  web:
    build: ./app
    container_name: devops-tracker-web
    ports:
      - "5000:5000"
    environment:
      # user:pass@host:port/dbname
      - DATABASE_URL=postgresql://tracker:tracker@db:5432/tracker
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: devops-tracker-db
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
      POSTGRES_DB: tracker
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

